// frontend/src/components/Navbar.jsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Menu, X, ChevronDown, LogOut } from 'lucide-react';
import { Button } from './ui/button';

const Navbar = () => {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [mobileProfileOpen, setMobileProfileOpen] = useState(false);
  const [profileSubOpen, setProfileSubOpen] = useState(false);
  const [visible, setVisible] = useState(true);
  const [lastScrollY, setLastScrollY] = useState(0);
  const navigate = useNavigate();

  useEffect(() => {
    const handleScroll = () => {
      const currentScrollY = window.scrollY;
      
      if (currentScrollY > lastScrollY && currentScrollY > 80) {
        // Scrolling down - hide navbar
        setVisible(false);
      } else {
        // Scrolling up - show navbar
        setVisible(true);
      }
      
      setLastScrollY(currentScrollY);
    };

    window.addEventListener('scroll', handleScroll, { passive: true });
    
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, [lastScrollY]);

  const handleLogout = () => {
    // Demo logout
    navigate('/');
  };

  return (
    <nav className={`bg-[#2C3E50] shadow-lg fixed w-full top-0 z-50 transition-transform duration-300 ${visible ? 'translate-y-0' : '-translate-y-full'}`}>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-20">
          {/* Logo */}
          <Link to="/" className="flex items-center gap-3 hover:opacity-90 transition-opacity">
            <div className="w-12 h-12">
              <img 
                src="/assets/images/logo.png" 
                alt="Rezerwujkort Logo"
                className="w-full h-full object-contain"
              />
            </div>
            <div className="flex flex-col">
              <h1 className="text-white text-2xl md:text-3xl font-bold tracking-tight leading-none uppercase">
                Rezerwujkort
              </h1>
              <span className="text-[#97c93c] text-xs md:text-sm font-medium uppercase tracking-wider">
                system rezerwacji online
              </span>
            </div>
          </Link>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center space-x-1">
            {/* Home Icon Button - Sprite */}
            <Link
              to="/"
              className="home-icon"
              aria-label="Strona główna"
            />
            <Link
              to="/sparingpartnerzy"
              className="px-4 py-2 text-white hover:text-[#A4C639] transition-colors duration-200 uppercase text-sm font-medium"
            >
              Sparingpartnerzy
            </Link>
            <Link
              to="/kluby"
              className="px-4 py-2 text-white hover:text-[#A4C639] transition-colors duration-200 uppercase text-sm font-medium"
            >
              Kluby
            </Link>
            <Link
              to="/turnieje"
              className="px-4 py-2 text-white hover:text-[#A4C639] transition-colors duration-200 uppercase text-sm font-medium"
            >
              Turnieje
            </Link>
            <Link
              to="/o-nas"
              className="px-4 py-2 text-white hover:text-[#A4C639] transition-colors duration-200 uppercase text-sm font-medium"
            >
              O nas
            </Link>
            
            {/* Profil Dropdown */}
            <div className="relative ml-4 dropdown-container">
              <button className="flex items-center gap-1 bg-[#A4C639] hover:bg-[#8FB82E] text-white font-semibold py-2 px-4 rounded transition-colors uppercase text-sm">
                Profil
                <ChevronDown size={16} />
              </button>
              
              {/* Dropdown Menu */}
              <div className="dropdown-menu absolute right-0 top-full mt-0 w-56 bg-white rounded-lg shadow-xl opacity-0 invisible transition-all duration-200 z-50">
                {/* Profil z podmenu - klikalne */}
                <div className="profile-submenu-container">
                  <button 
                    className="w-full flex items-center justify-between px-4 py-3 text-gray-700 hover:bg-gray-100 cursor-pointer rounded-t-lg font-medium"
                    onClick={() => setProfileSubOpen(!profileSubOpen)}
                  >
                    <span>Profil</span>
                    <ChevronDown size={14} className={`transform transition-transform ${profileSubOpen ? 'rotate-180' : ''}`} />
                  </button>
                  {/* Podmenu Profil - rozwija się w dół */}
                  <div className={`overflow-hidden transition-all duration-300 ${profileSubOpen ? 'max-h-48' : 'max-h-0'}`}>
                    <Link
                      to="/profil/dane"
                      className="block px-6 py-2 text-gray-600 hover:bg-gray-100 hover:text-[#A4C639] text-sm"
                    >
                      Twoje dane
                    </Link>
                    <Link
                      to="/profil/edytuj"
                      className="block px-6 py-2 text-gray-600 hover:bg-gray-100 hover:text-[#A4C639] text-sm"
                    >
                      Edytuj profil
                    </Link>
                    <Link
                      to="/profil/zmiana-hasla"
                      className="block px-6 py-2 text-gray-600 hover:bg-gray-100 hover:text-[#A4C639] text-sm"
                    >
                      Zmiana hasła
                    </Link>
                    <Link
                      to="/profil/usun-konto"
                      className="block px-6 py-2 text-gray-600 hover:bg-gray-100 hover:text-[#A4C639] text-sm"
                    >
                      Usuń konto
                    </Link>
                  </div>
                </div>
                
                <Link
                  to="/profil/rezerwacje"
                  className="block px-4 py-3 text-gray-700 hover:bg-gray-100 hover:text-[#A4C639] font-medium"
                >
                  Rezerwacje
                </Link>
                <Link
                  to="/profil/karnety"
                  className="block px-4 py-3 text-gray-700 hover:bg-gray-100 hover:text-[#A4C639] font-medium"
                >
                  Karnety
                </Link>
                <Link
                  to="/moje-ogloszenia"
                  className="block px-4 py-3 text-gray-700 hover:bg-gray-100 hover:text-[#A4C639] font-medium"
                >
                  Sparingpartnerzy
                </Link>
                
                {/* Wyloguj - czerwony przycisk */}
                <div className="border-t border-gray-200 mt-2 pt-2 px-3 pb-3">
                  <button
                    onClick={handleLogout}
                    className="w-full flex items-center justify-center gap-2 bg-red-500 hover:bg-red-600 text-white font-semibold py-2 px-4 rounded transition-colors"
                  >
                    <LogOut size={16} />
                    Wyloguj
                  </button>
                </div>
              </div>
            </div>
          </div>

          {/* Mobile menu button */}
          <button
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            className="md:hidden text-white p-2 rounded-lg hover:bg-[#34495E] transition-colors"
          >
            {mobileMenuOpen ? <X size={24} /> : <Menu size={24} />}
          </button>
        </div>
      </div>

      {/* Mobile Menu */}
      {mobileMenuOpen && (
        <div className="md:hidden bg-[#34495E] border-t border-[#4A5F7F]">
          <div className="px-4 py-3 space-y-2">
            <Link
              to="/"
              onClick={() => setMobileMenuOpen(false)}
              className="flex items-center gap-3 px-4 py-2 text-white hover:bg-[#2C3E50] rounded transition-colors"
            >
              <div className="home-icon-small" />
              Strona główna
            </Link>
            <Link
              to="/sparingpartnerzy"
              onClick={() => setMobileMenuOpen(false)}
              className="block px-4 py-2 text-white hover:bg-[#2C3E50] rounded transition-colors uppercase text-sm"
            >
              Sparingpartnerzy
            </Link>
            <Link
              to="/kluby"
              onClick={() => setMobileMenuOpen(false)}
              className="block px-4 py-2 text-white hover:bg-[#2C3E50] rounded transition-colors uppercase text-sm"
            >
              Kluby
            </Link>
            <Link
              to="/turnieje"
              onClick={() => setMobileMenuOpen(false)}
              className="block px-4 py-2 text-white hover:bg-[#2C3E50] rounded transition-colors uppercase text-sm"
            >
              Turnieje
            </Link>
            <Link
              to="/o-nas"
              onClick={() => setMobileMenuOpen(false)}
              className="block px-4 py-2 text-white hover:bg-[#2C3E50] rounded transition-colors uppercase text-sm"
            >
              O nas
            </Link>
            
            {/* Mobile Profil Menu */}
            <div className="border-t border-[#4A5F7F] pt-2 mt-2">
              <button
                onClick={() => setMobileProfileOpen(!mobileProfileOpen)}
                className="w-full flex items-center justify-between px-4 py-2 text-white hover:bg-[#2C3E50] rounded transition-colors uppercase text-sm font-semibold"
              >
                Profil
                <ChevronDown size={16} className={`transform transition-transform ${mobileProfileOpen ? 'rotate-180' : ''}`} />
              </button>
              
              {mobileProfileOpen && (
                <div className="ml-4 space-y-1 mt-1">
                  <Link
                    to="/profil/dane"
                    onClick={() => setMobileMenuOpen(false)}
                    className="block px-4 py-2 text-gray-300 hover:bg-[#2C3E50] hover:text-white rounded transition-colors text-sm"
                  >
                    Twoje dane
                  </Link>
                  <Link
                    to="/profil/edytuj"
                    onClick={() => setMobileMenuOpen(false)}
                    className="block px-4 py-2 text-gray-300 hover:bg-[#2C3E50] hover:text-white rounded transition-colors text-sm"
                  >
                    Edytuj profil
                  </Link>
                  <Link
                    to="/profil/zmiana-hasla"
                    onClick={() => setMobileMenuOpen(false)}
                    className="block px-4 py-2 text-gray-300 hover:bg-[#2C3E50] hover:text-white rounded transition-colors text-sm"
                  >
                    Zmiana hasła
                  </Link>
                  <Link
                    to="/profil/usun-konto"
                    onClick={() => setMobileMenuOpen(false)}
                    className="block px-4 py-2 text-gray-300 hover:bg-[#2C3E50] hover:text-white rounded transition-colors text-sm"
                  >
                    Usuń konto
                  </Link>
                  <Link
                    to="/profil/rezerwacje"
                    onClick={() => setMobileMenuOpen(false)}
                    className="block px-4 py-2 text-gray-300 hover:bg-[#2C3E50] hover:text-white rounded transition-colors text-sm"
                  >
                    Rezerwacje
                  </Link>
                  <Link
                    to="/profil/karnety"
                    onClick={() => setMobileMenuOpen(false)}
                    className="block px-4 py-2 text-gray-300 hover:bg-[#2C3E50] hover:text-white rounded transition-colors text-sm"
                  >
                    Karnety
                  </Link>
                  <Link
                    to="/moje-ogloszenia"
                    onClick={() => setMobileMenuOpen(false)}
                    className="block px-4 py-2 text-gray-300 hover:bg-[#2C3E50] hover:text-white rounded transition-colors text-sm"
                  >
                    Sparingpartnerzy
                  </Link>
                  <button
                    onClick={() => {
                      setMobileMenuOpen(false);
                      handleLogout();
                    }}
                    className="w-full flex items-center gap-2 px-4 py-2 text-red-400 hover:bg-red-500 hover:text-white rounded transition-colors text-sm font-semibold mt-2"
                  >
                    <LogOut size={16} />
                    Wyloguj
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Styles for sprite icons and dropdown */}
      <style>{`
        .home-icon {
          width: 50px;
          height: 50px;
          background: url('/assets/images/home.png') no-repeat 0 0;
          background-size: 50px auto;
          cursor: pointer;
          display: block;
        }
        .home-icon:hover {
          background-position: 0 -50px;
        }
        
        .home-icon-small {
          width: 24px;
          height: 24px;
          background: url('/assets/images/home.png') no-repeat 0 0;
          background-size: 24px auto;
        }
        
        /* Dropdown styles */
        .dropdown-container:hover .dropdown-menu {
          opacity: 1;
          visibility: visible;
        }
        
        .dropdown-menu {
          padding-top: 8px;
        }
        
        .dropdown-menu::before {
          content: '';
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          height: 8px;
          background: transparent;
        }
      `}</style>
    </nav>
  );
};

export default Navbar;

// angular_navbar/navbar.component.ts
import { Component, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent {
  mobileMenuOpen = false;
  mobileProfileOpen = false;
  profileSubOpen = false;
  
  // Hide on scroll
  visible = true;
  lastScrollY = 0;

  @HostListener('window:scroll', [])
  onWindowScroll(): void {
    const currentScrollY = window.scrollY;
    
    if (currentScrollY > this.lastScrollY && currentScrollY > 80) {
      // Scrolling down - hide navbar
      this.visible = false;
    } else {
      // Scrolling up - show navbar
      this.visible = true;
    }
    
    this.lastScrollY = currentScrollY;
  }

  toggleMobileMenu(): void {
    this.mobileMenuOpen = !this.mobileMenuOpen;
  }

  closeMobileMenu(): void {
    this.mobileMenuOpen = false;
  }

  toggleMobileProfile(): void {
    this.mobileProfileOpen = !this.mobileProfileOpen;
  }

  toggleProfileSub(): void {
    this.profileSubOpen = !this.profileSubOpen;
  }

  handleLogout(): void {
    // Demo logout - redirect to home
    window.location.href = '/';
  }
}

<nav class="navbar" [class.hidden]="!visible">
  <div class="navbar-container">
    <div class="navbar-content">
      <!-- Logo -->
      <a routerLink="/" class="logo-link">
        <div class="logo-image">
          <img src="/assets/images/logo.png" alt="Rezerwujkort Logo" />
        </div>
        <div class="logo-text">
          <h1 class="logo-title">Rezerwujkort</h1>
          <span class="logo-subtitle">system rezerwacji online</span>
        </div>
      </a>

      <!-- Desktop Navigation -->
      <div class="desktop-nav">
        <!-- Home Icon -->
        <a routerLink="/" class="home-icon" aria-label="Strona główna"></a>
        
        <a routerLink="/sparingpartnerzy" class="nav-link">Sparingpartnerzy</a>
        <a routerLink="/kluby" class="nav-link">Kluby</a>
        <a routerLink="/turnieje" class="nav-link">Turnieje</a>
        <a routerLink="/o-nas" class="nav-link">O nas</a>

        <!-- Profil Dropdown -->
        <div class="dropdown-container">
          <button class="profile-button">
            Profil
            <svg class="chevron-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
            </svg>
          </button>

          <!-- Dropdown Menu -->
          <div class="dropdown-menu">
            <!-- Profil z podmenu -->
            <div class="profile-submenu-container">
              <button class="submenu-trigger" (click)="toggleProfileSub()">
                <span>Profil</span>
                <svg class="chevron-icon" [class.rotated]="profileSubOpen" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                </svg>
              </button>
              
              <!-- Podmenu Profil -->
              <div class="profile-submenu" [class.open]="profileSubOpen">
                <a routerLink="/profil/dane" class="submenu-link">Twoje dane</a>
                <a routerLink="/profil/edytuj" class="submenu-link">Edytuj profil</a>
                <a routerLink="/profil/zmiana-hasla" class="submenu-link">Zmiana hasła</a>
                <a routerLink="/profil/usun-konto" class="submenu-link">Usuń konto</a>
              </div>
            </div>

            <a routerLink="/profil/rezerwacje" class="dropdown-link">Rezerwacje</a>
            <a routerLink="/profil/karnety" class="dropdown-link">Karnety</a>
            <a routerLink="/moje-ogloszenia" class="dropdown-link">Sparingpartnerzy</a>

            <!-- Wyloguj -->
            <div class="logout-container">
              <button class="logout-button" (click)="handleLogout()">
                <svg class="logout-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
                </svg>
                Wyloguj
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- Mobile menu button -->
      <button class="mobile-menu-button" (click)="toggleMobileMenu()">
        <svg *ngIf="!mobileMenuOpen" class="menu-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
        </svg>
        <svg *ngIf="mobileMenuOpen" class="menu-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
        </svg>
      </button>
    </div>
  </div>

  <!-- Mobile Menu -->
  <div class="mobile-menu" *ngIf="mobileMenuOpen">
    <div class="mobile-menu-content">
      <a routerLink="/" class="mobile-link" (click)="closeMobileMenu()">
        <div class="home-icon-small"></div>
        Strona główna
      </a>
      <a routerLink="/sparingpartnerzy" class="mobile-link" (click)="closeMobileMenu()">Sparingpartnerzy</a>
      <a routerLink="/kluby" class="mobile-link" (click)="closeMobileMenu()">Kluby</a>
      <a routerLink="/turnieje" class="mobile-link" (click)="closeMobileMenu()">Turnieje</a>
      <a routerLink="/o-nas" class="mobile-link" (click)="closeMobileMenu()">O nas</a>

      <!-- Mobile Profil Menu -->
      <div class="mobile-profile-section">
        <button class="mobile-profile-trigger" (click)="toggleMobileProfile()">
          Profil
          <svg class="chevron-icon" [class.rotated]="mobileProfileOpen" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
          </svg>
        </button>

        <div class="mobile-profile-menu" *ngIf="mobileProfileOpen">
          <a routerLink="/profil/dane" class="mobile-submenu-link" (click)="closeMobileMenu()">Twoje dane</a>
          <a routerLink="/profil/edytuj" class="mobile-submenu-link" (click)="closeMobileMenu()">Edytuj profil</a>
          <a routerLink="/profil/zmiana-hasla" class="mobile-submenu-link" (click)="closeMobileMenu()">Zmiana hasła</a>
          <a routerLink="/profil/usun-konto" class="mobile-submenu-link" (click)="closeMobileMenu()">Usuń konto</a>
          <a routerLink="/profil/rezerwacje" class="mobile-submenu-link" (click)="closeMobileMenu()">Rezerwacje</a>
          <a routerLink="/profil/karnety" class="mobile-submenu-link" (click)="closeMobileMenu()">Karnety</a>
          <a routerLink="/moje-ogloszenia" class="mobile-submenu-link" (click)="closeMobileMenu()">Sparingpartnerzy</a>
          <button class="mobile-logout-button" (click)="handleLogout()">
            <svg class="logout-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
            </svg>
            Wyloguj
          </button>
        </div>
      </div>
    </div>
  </div>
</nav>
